// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7z08WPRDIUYy8sNhurOmxSMoqZmeFJFI',
    appId: '1:634658773502:web:18a98766f00fe49b9d88af',
    messagingSenderId: '634658773502',
    projectId: 'taxidex-4a53e',
    authDomain: 'taxidex-4a53e.firebaseapp.com',
    databaseURL: 'https://taxidex-4a53e-default-rtdb.firebaseio.com',
    storageBucket: 'taxidex-4a53e.appspot.com',
    measurementId: 'G-XN0D53K11X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCOz9Mft4sVvBIWaQpgkjt-FMwtJsdpAE',
    appId: '1:634658773502:android:65229255b1d9afad9d88af',
    messagingSenderId: '634658773502',
    projectId: 'taxidex-4a53e',
    databaseURL: 'https://taxidex-4a53e-default-rtdb.firebaseio.com',
    storageBucket: 'taxidex-4a53e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPySAyzx1sjaChzsGtlhy48VGXPF8F__c',
    appId: '1:634658773502:ios:8fa3b564ad084efc9d88af',
    messagingSenderId: '634658773502',
    projectId: 'taxidex-4a53e',
    databaseURL: 'https://taxidex-4a53e-default-rtdb.firebaseio.com',
    storageBucket: 'taxidex-4a53e.appspot.com',
    androidClientId: '634658773502-dc1qpoid9p8103ei13jc6o5glfco412k.apps.googleusercontent.com',
    iosClientId: '634658773502-nsnpl805mkd8vnd50nhnbhrpo6fkt7ah.apps.googleusercontent.com',
    iosBundleId: 'com.taxidex.user',
  );
}
